# Generated by Django 4.1.1 on 2022-09-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient", name="age", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="patient",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
