# Generated by Django 4.1.1 on 2022-09-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_patient_age_patient_weight"),
    ]

    operations = [
        migrations.RenameModel(old_name="Patient", new_name="PatientModel",),
        migrations.RenameField(
            model_name="patientmodel", old_name="last_name", new_name="lastname",
        ),
    ]
