# Generated by Django 4.1.1 on 2022-09-29 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_patient_patientmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiseasesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "causes",
                    models.FileField(max_length=1000, upload_to="File/disease/causes/"),
                ),
                (
                    "treatments",
                    models.FileField(
                        max_length=1000, upload_to="File/disease/treatments/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicineModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "definition",
                    models.FileField(
                        max_length=1000, upload_to="File/medicine/definition/"
                    ),
                ),
                (
                    "warnings",
                    models.FileField(
                        max_length=1000, upload_to="File/medicine/warnings/"
                    ),
                ),
                (
                    "prescription",
                    models.FileField(
                        max_length=1000, upload_to="File/medicine/prescription/"
                    ),
                ),
                (
                    "effects",
                    models.FileField(
                        max_length=1000, upload_to="File/medicine/effects/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True)),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.diseasesmodel",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.medicinemodel",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.patientmodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="diseasesmodel",
            name="medicine1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medicine1",
                to="main.medicinemodel",
            ),
        ),
        migrations.AddField(
            model_name="diseasesmodel",
            name="medicine2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medicine2",
                to="main.medicinemodel",
            ),
        ),
    ]
