# Generated by Django 4.1.1 on 2022-09-29 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_diseasesmodel_medicinemodel_historymodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientmodel",
            name="image",
            field=models.ImageField(
                default="static/images/logo.jpg", upload_to="File/Images/patient/"
            ),
        ),
        migrations.CreateModel(
            name="DoctorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "image",
                    models.ImageField(
                        default="static/images/logo.jpg",
                        upload_to="File/Images/doctor/",
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.diseasesmodel",
                    ),
                ),
            ],
        ),
    ]
