# Generated by Django 4.1.1 on 2022-09-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_patientmodel_image_doctormodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="diseasesmodel",
            name="definition",
            field=models.FileField(
                default="static/images/file.txt",
                max_length=1000,
                upload_to="File/disease/definition/",
            ),
        ),
    ]
