# Generated by Django 4.1.1 on 2022-09-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_diseasesmodel_definition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicinemodel",
            name="definition",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="medicinemodel",
            name="effects",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="medicinemodel",
            name="prescription",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="medicinemodel",
            name="warnings",
            field=models.CharField(max_length=200),
        ),
    ]
