# Generated by Django 4.1.1 on 2022-09-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_medicinemodel_definition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diseasesmodel",
            name="causes",
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name="diseasesmodel",
            name="definition",
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name="diseasesmodel",
            name="treatments",
            field=models.CharField(max_length=700),
        ),
    ]
