# Generated by Django 4.1.1 on 2022-10-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_registrationmodel_confirm"),
    ]

    operations = [
        migrations.AddField(
            model_name="diseasesmodel",
            name="preventions",
            field=models.CharField(default="", max_length=700),
        ),
    ]
