# Generated by Django 4.1.1 on 2022-10-03 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_profile_delete_registrationmodel"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="username",),
    ]
