# Generated by Django 4.1.1 on 2022-10-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_pneumoniamodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pneumoniamodel",
            name="image",
            field=models.ImageField(
                default="static/images/logo.jpg", upload_to="File/disease/pneumonia/"
            ),
        ),
    ]
