# Generated by Django 4.1.1 on 2022-10-12 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_pneumoniacancermodel_delete_pneumoniamodel"),
    ]

    operations = [
        migrations.RemoveField(model_name="diseasesmodel", name="medicine2",),
        migrations.AlterField(
            model_name="diseasesmodel",
            name="medicine1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.medicinemodel"
            ),
        ),
    ]
