# Generated by Django 4.1.1 on 2022-10-12 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_remove_diseasesmodel_medicine2_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="diseasesmodel", name="medicine1",),
        migrations.AddField(
            model_name="medicinemodel",
            name="disease",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.diseasesmodel",
            ),
        ),
    ]
