# Generated by Django 4.1.1 on 2022-10-26 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_discussion"),
    ]

    operations = [
        migrations.RemoveField(model_name="patientmodel", name="email",),
        migrations.RemoveField(model_name="patientmodel", name="lastname",),
        migrations.RemoveField(model_name="patientmodel", name="name",),
        migrations.AddField(
            model_name="doctormodel",
            name="profile",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.profile",
            ),
        ),
        migrations.AddField(
            model_name="patientmodel",
            name="address",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="patientmodel",
            name="doctor",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.doctormodel",
            ),
        ),
        migrations.AddField(
            model_name="patientmodel",
            name="profile",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.profile",
            ),
        ),
        migrations.AlterField(
            model_name="doctormodel",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="doctormodel",
            name="specialty",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="patientmodel",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
