# Generated by Django 4.1.1 on 2022-10-26 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_remove_patientmodel_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="doctormodel", name="name",),
        migrations.AlterField(
            model_name="patientmodel",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.doctormodel"
            ),
        ),
        migrations.AlterField(
            model_name="patientmodel",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="main.profile"
            ),
        ),
    ]
