# Generated by Django 4.1.1 on 2022-10-26 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_remove_doctormodel_name_alter_patientmodel_doctor_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="patientmodel", name="image",),
    ]
