# Generated by Django 4.1.1 on 2022-10-26 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_patientmodel_image"),
    ]

    operations = [
        migrations.RenameModel(old_name="PatientModel", new_name="PatientsModel",),
    ]
