# Generated by Django 4.1.1 on 2022-10-26 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_alter_patientsmodel_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="discussion", name="user",),
        migrations.AddField(
            model_name="discussion",
            name="doctor",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.doctormodel",
            ),
        ),
        migrations.AddField(
            model_name="discussion",
            name="patient",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.patientsmodel",
            ),
        ),
    ]
