# Generated by Django 4.1.1 on 2022-10-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_appointmentsmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentsmodel", name="date", field=models.DateField(),
        ),
    ]
