# Generated by Django 4.1.1 on 2022-10-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0033_alter_appointmentsmodel_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentsmodel", name="date", field=models.DateTimeField(),
        ),
    ]
