# Generated by Django 4.1.1 on 2022-10-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0034_alter_appointmentsmodel_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentsmodel",
            name="date",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="appointmentsmodel",
            name="slot",
            field=models.CharField(max_length=20),
        ),
    ]
