# Generated by Django 4.1.1 on 2022-10-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_alter_appointmentsmodel_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentsmodel",
            name="date",
            field=models.DateField(blank=True),
        ),
    ]
